// Every wrestler currently in the roster (see RosterData.ts), kept separate
// so hometowns can be filled in here without touching the roster data
// itself. Leave a value as "" to show "Unknown" in the wrestler profile
// pop-up; fill it in (e.g. "Cardiff, Wales") to have it displayed there.
export const RosterHometowns: Record<string, string> = {
  "Abyss": "Washington, D.C.",
  "AJ Lee": "Union City, New Jersey",
  "AJ Styles": "Gainesville, Georgia",
  "Akam": "",
  "Akira Tozawa": "Kobe, Japan",
  "Alba Fyre": "Johnstone, Scotland",
  "Aleister Black": "Amsterdam, Netherlands",
  "Alex Shelley": "Detroit, Michigan",
  "Alexa Bliss": "Columbus, Ohio",
  "Andrade": "Gómez Palacio, Durango, Mexico",
  "Andre Chase": "Draper, North Carolina",
  "Angel": "Monterrey, Mexico",
  "Angelo Dawkins": "Cincinnati, Ohio",
  "Apollo Crews": "Stone Mountain, Georgia",
  "Ashante Thee Adonis": "Hammonton, New Jersey",
  "Asuka": "Osaka, Japan",
  "Austin Theory": "Atlanta, Georgia",
  "Axiom": "Madrid, Spain",
  "B Fab": "Canton, Ohio",
  "Baron Corbin": "Kansas City, Missouri",
  "Batista": "Washington, D.C.",
  "Bayley": "San Jose, California",
  "Becky Lynch": "Dublin, Ireland",
  "Berto": "Monterrey, Mexico",
  "Bianca Belair": "Knoxville, Tennessee",
  "Big E": "Tampa, Florida",
  "Billy Gunn": "Austin, Texas",
  "Blair Davenport": "Wellington, New Zealand",
  "Blake Monroe": "London, England",
  "Boogeyman": "Phoenix, Arizona",
  "Booker T": "Houston, Texas",
  "Braun Strowman": "Sherrills Ford, North Carolina",
  "Bray Wyatt": "Brooksville, Florida",
  "Brock Lesnar": "Minneapolis, Minnesota",
  "Bron Breakker": "Atlanta, Georgia",
  "Bronson Reed": "Black Forest, Australia",
  "Brooks Jensen": "Ranburne, Alabama",
  "Brutus Creed": "Lexington, Ohio",
  "Bubba Ray Dudley": "Queens, New York",
  "Bull Nakano": "Kawaguchi, Japan",
  "CM Punk": "Chicago, Illinois",
  "Cactus Jack": "Truth or Consequences, New Mexico",
  "Candice LeRae": "Riverside, California",
  "Carlito": "San Juan, Puerto Rico",
  "Carmella": "Staten Island, New York",
  "Carmelo Hayes": "Boston, Massachusetts",
  "Cedric Alexander": "Charlotte, North Carolina",
  "Chad Gable": "Minneapolis, Minnesota",
  "Channing Lorenzo": "Albany, New York",
  "Charlie Dempsey": "Blackpool, England",
  "Charlotte Flair": "Charlotte, North Carolina",
  "Chelsea Green": "Victoria, British Columbia, Canada",
  "Chris Sabin": "Detroit, Michigan",
  "Chyna": "Londonderry, New Hampshire",
  "Cody Rhodes": "Atlanta, Georgia",
  "Cora Jade": "Chicago, Illinois",
  "Cruz Del Toro": "Córdoba, Veracruz, Mexico",
  "D-Lo Brown": "Chicago, Illinois",
  "D-Von Dudley": "New Rochelle, New York",
  "DDP": "Point Pleasant, New Jersey",
  "Dakota Kai": "Auckland, New Zealand",
  "Damian Priest": "New York, New York",
  "Dexter Lumis": "Recluse, Wyoming",
  "Diesel": "Detroit, Michigan",
  "Doink The Clown": "",
  "Dominik Mysterio": "San Diego, California",
  "Dragon Lee": "Tala, Jalisco, Mexico",
  "Drew Mcintyre": "Ayr, Scotland",
  "Dude Love": "Truth or Consequences, New Mexico",
  "Duke Hudson": "Adelaide, South Australia, Australia",
  "Dusty Rhodes": "Austin, Texas",
  "Eddie Guerrero": "El Paso, Texas",
  "Eddy Thorpe": "Reno, Nevada",
  "Elektra Lopez": "San Juan, Puerto Rico",
  "El Grande Americano": "",
  "El Hijo Del Vikingo": "Puebla, Mexico",
  "Elton Prince": "",
  "Eric Bischoff": "Detroit, Michigan",
  "Erick Rowan": "Minneapolis, Minnesota",
  "Erik": "Cleveland, Ohio",
  "Ethan Page": "Hamilton, Ontario, Canada",
  "Eve Torres": "Denver, Colorado",
  "Faarooq": "Warner Robins, Georgia",
  "Fallon Henley": "Chelsea, Michigan",
  "Finn Balor": "Bray, Ireland",
  "Flammer": "San Nicolás, Nuevo León, Mexico",
  "Gigi Dolin": "Atlanta, Georgia",
  "Giovanni Vinci": "South Tyrol, Italy",
  "Giulia": "Tokyo, Japan",
  "Goldberg": "Atlanta, Georgia",
  "Grayson Waller": "Sydney, Australia",
  "Gunther": "Vienna, Austria",
  "Hank Walker": "Hampstead, North Carolina",
  "Honky Tonk Man": "Memphis, Tennessee",
  "HulkHogan": "Venice Beach, California",
  "Ilja Dragunov": "Dresden, Germany",
  "Indi Hartwell": "Melbourne, Australia",
  "Isla Dawn": "Glasgow, Scotland",
  "Ivar": "Lynn, Massachusetts",
  "Ivy Nile": "Knoxville, Tennessee",
  "Iyo Sky": "Tokyo, Japan",
  "Izzi Dame": "Buchanan, Michigan",
  "Jacob Fatu": "Sacramento, California",
  "Jacy Jayne": "Jersey City, New Jersey",
  "Jade Cargill": "Vero Beach, Florida",
  "Jaida Parker": "Port St. Lucie, Florida",
  "Jakara Jackson": "Albuquerque, New Mexico",
  "Jake The Snake Roberts": "Stone Mountain, Georgia",
  "Jazmyn Nyx": "Syracuse, New York",
  "JBL": "New York City, New York",
  "JC Mateo": "Honolulu, Hawaii",
  "JD Mcdonagh": "Bray, Ireland",
  "Jeff Hardy": "Cameron, North Carolina",
  "Je'von Evans": "Greensboro, North Carolina",
  "Jesse Ventura": "Brooklyn Park, Minnesota",
  "Jey Uso": "San Francisco, California",
  "Jim Neidhart": "Reno, Nevada",
  "Jimmy Uso": "San Francisco, California",
  "Joaquin Wilde": "Chicago, Illinois",
  "Joe Coffey": "Glasgow, Scotland",
  "Joe Gacy": "Badstow, New Jersey",
  "Joe Hendry": "Edinburgh, Scotland",
  "John Cena": "West Newbury, Massachusetts",
  "Johnny Gargano": "Cleveland, Ohio",
  "Jordynne Grace": "Austin, Texas",
  "Josh Briggs": "Nothing, Arizona",
  "Julius Creed": "Lexington, Ohio",
  "Junkyard Dog": "Charlotte, North Carolina",
  "KSI": "Watford, England",
  "Kairi Sane": "Yamaguchi, Japan",
  "Kane": "",
  "Karl Anderson": "Tokyo, Japan",
  "Karmen Petrovic": "Toronto, Ontario, Canada",
  "Karrion Kross": "Las Vegas, Nevada",
  "Katana Chance": "Belleville, New Jersey",
  "Kayden Carter": "The Philippine Islands",
  "Kelani Jordan": "Boynton Beach, Florida",
  "Ken Shamrock": "Sacramento, California",
  "Kevin Nash": "Detroit, Michigan",
  "Kevin Owens": "Marieville, Quebec, Canada",
  "Kiana James": "Sioux City, Iowa",
  "Kit Wilson": "Buckinghamshire, England",
  "Kofi Kingston": "Ghana, West Africa",
  "Kurt Angle": "Pittsburgh, Pennsylvania",
  "LA Knight": "Los Angeles, California",
  "La Parka": "Hermosillo, Sonora, Mexico",
  "Lash Legend": "Atlanta, Georgia",
  "Lex Luger": "Chicago, Illinois",
  "Lexis King": "Cincinnati, Ohio",
  "Lita": "Sanford, North Carolina",
  "Liv Morgan": "Elmwood Park, New Jersey",
  "Logan Paul": "Westlake, Ohio",
  "Lola Vice": "Miami, Florida",
  "Ludwig Kaiser": "Hamburg, Germany",
  "Luke Gallows": "Chicago, Illinois",
  "Lyra Valkyria": "Dublin, Ireland",
  "Macho Man Randy Savage": "Sarasota, Florida",
  "Mankind": "Long Island, New York",
  "Mark Coffey": "Glasgow, Scotland",
  "Mark Henry": "Silsbee, Texas",
  "Maryse": "Montreal, Quebec, Canada",
  "Matt Cardona": "Long Island, New York",
  "Matt Hardy": "Cameron, North Carolina",
  "Maxxine Dupri": "Sacramento, California",
  "Michelle McCool": "Palatka, Florida",
  "Michin": "Fontana, California",
  "Mick Foley": "Long Island, New York",
  "Molly Holly": "Forest Lake, Minnesota",
  "Montez Ford": "Chicago, Illinois",
  "Mr Iguana": "Culiacán, Sinaloa, Mexico",
  "Mr Perfect": "Robbinsdale, Minnesota",
  "Myles Borne": "Wilmington, North Carolina",
  "Naomi": "Orlando, Florida",
  "Natalya": "Calgary, Alberta, Canada",
  "Nathan Frazer": "Jersey, Channel Islands",
  "New Jack": "Los Angeles, California",
  "Nia Jax": "San Diego, California",
  "Nikki Bella": "Scottsdale, Arizona",
  "Nikki Cross": "Glasgow, Scotland",
  "Nikkita Lyons": "Los Angeles, California",
  "Noam Dar": "Ayr, Scotland",
  "Oba Femi": "Lagos, Nigeria",
  "Omos": "Lagos, Nigeria",
  "Oro Mensah": "Ghana, West Africa",
  "Otis": "Duluth, Minnesota",
  "Pat Mcafee": "Plum, Pennsylvania",
  "Paul Orndorff": "Brandon, Florida",
  "Penta": "Ecatepec, Mexico",
  "Pete Dunne": "Birmingham, England",
  "Piper Niven": "Ayrshire, Scotland",
  "Psycho Clown": "Mexico City, Mexico",
  "R-Truth": "Charlotte, North Carolina",
  "Randy Orton": "St. Louis, Missouri",
  "Raquel Rodriguez": "Rio Grande Valley, Texas",
  "Razor Ramon": "Miami, Florida",
  "Rey Fenix": "Ecatepec, Mexico",
  "Rey Mysterio": "San Diego, California",
  "Rezar": "Amsterdam, Netherlands",
  "Rhea Ripley": "Adelaide, Australia",
  "Ricky Saints": "New Orleans, Louisiana",
  "Ricky Steamboat": "Honolulu, Hawaii",
  "Ridge Holland": "Yorkshire, England",
  "Rikishi": "Isle of Samoa",
  "Road Dogg": "Marietta, Georgia",
  "Rob Van Dam": "Battle Creek, Michigan",
  "Roddy Piper": "Glasgow, Scotland",
  "Roman Reigns": "Pensacola, Florida",
  "Rosey": "San Francisco, California",
  "Roxanne Perez": "Laredo, Texas",
  "Rusev": "Bulgaria",
  "Sami Zayn": "Montreal, Quebec, Canada",
  "Sandman": "Philadelphia, Pennsylvania",
  "Santos Escobar": "Mexico City, Mexico",
  "Scarlett": "Chicago, Illinois",
  "Scott Hall": "Miami, Florida",
  "Scott Steiner": "Detroit, Michigan",
  "Seth Rollins": "Davenport, Iowa",
  "Shawn Michaels": "San Antonio, Texas",
  "Shawn Spears": "Niagara Falls, Ontario, Canada",
  "Shayna Baszler": "Sioux Falls, South Dakota",
  "Sheamus": "Dublin, Ireland",
  "Shinsuke Nakamura": "Kyoto, Japan",
  "Shotzi": "Oakland, California",
  "Sid Justice": "West Memphis, Arkansas",
  "Sol Ruca": "Honolulu, Hawaii",
  "Solo Sikoa": "Las Vegas, Nevada",
  "Sonya Deville": "Shamong, New Jersey",
  "Stacy Keibler": "Baltimore, Maryland",
  "Stardust": "",
  "Stephanie Mcmahon": "Greenwich, Connecticut",
  "Stephanie Vaquer": "San Fernando, Chile",
  "Stone Cold Steve Austin": "Victoria, Texas",
  "Syxx": "Minneapolis, Minnesota",
  "Talla Tonga": "Kissimmee, Florida",
  "Tama Tonga": "Nuku'alofa, Tonga",
  "Tamina": "Pacific Islands",
  "Tank Ledger": "Chicago, Illinois",
  "Tatum Paxley": "Dallas, Texas",
  "Tavion Hights": "Fountain, Colorado",
  "Tegan Nox": "Welsh Valleys, Wales",
  "Terry Funk": "Amarillo, Texas",
  "Fiend": "",
  "The Great Khali": "Punjab, India",
  "The Great Muta": "Tokyo, Japan",
  "The Hurricane": "",
  "The Iron Sheik": "Tehran, Iran",
  "Miz": "Hollywood, California",
  "Rock": "Miami, Florida",
  "Thea Hail": "Pittsburgh, Pennsylvania",
  "Tiffany Stratton": "Minneapolis, Minnesota",
  "Tito Santana": "Tocula, Mexico",
  "Tommaso Ciampa": "Boston, Massachusetts",
  "Tonga Loa": "Honolulu, Hawaii",
  "Tony D'Angelo": "Chicago, Illinois",
  "Torrie Wilson": "Boise, Idaho",
  "Trick Williams": "Columbia, South Carolina",
  "Triple H": "Greenwich, Connecticut",
  "Trish Stratus": "Toronto, Ontario, Canada",
  "Tyler Bate": "Dudley, England",
  "Tyler Breeze": "Penticton, British Columbia, Canada",
  "Ultimate Warrior": "Parts Unknown",
  "Umaga": "Isle of Samoa",
  "Uncle Howdy": "",
  "Undertaker": "Death Valley",
  "Vader": "Boulder, Colorado",
  "Valhalla": "Louisville, Kentucky",
  "Victoria": "San Bernardino, California",
  "Wade Barrett": "Preston, England",
  "Wendy Choo": "New York, New York",
  "Wes Lee": "Dayton, Ohio",
  "William Regal": "Blackpool, England",
  "Wolfgang": "Glasgow, Scotland",
  "Wren Sinclair": "Dallas, Texas",
  "X-Pac": "Minneapolis, Minnesota",
  "Xavier Woods": "Atlanta, Georgia",
  "Yokozuna": "The Land of the Rising Sun",
  "Yoshiki Inamura": "Ōtawara, Japan",
  "Zaria": "Adelaide, South Australia",
  "ZelinaVega": "Queens, New York",
  "Zoey Stark": "Las Vegas, Nevada",
};
