// Every wrestler currently in the roster (see RosterData.ts), kept separate
// so hometowns can be filled in here without touching the roster data
// itself. Leave a value as "" to show "Unknown" in the wrestler profile
// pop-up; fill it in (e.g. "Cardiff, Wales") to have it displayed there.
export const RosterHometowns: Record<string, string> = {
  "Abyss": "",
  "AJ Lee": "",
  "AJ Styles": "",
  "Akam": "",
  "Akira Tozawa": "",
  "Alba Fyre": "",
  "Aleister Black": "",
  "Alex Shelley": "",
  "Alexa Bliss": "",
  "Andrade": "",
  "Andre Chase": "",
  "Angel": "",
  "Angelo Dawkins": "",
  "Apollo Crews": "",
  "Ashante Thee Adonis": "",
  "Asuka": "",
  "Austin Theory": "",
  "Axiom": "",
  "B Fab": "",
  "Baron Corbin": "",
  "Batista": "",
  "Bayley": "",
  "Becky Lynch": "",
  "Berto": "",
  "Bianca Belair": "",
  "Big E": "",
  "Billy Gunn": "",
  "Blair Davenport": "",
  "Blake Monroe": "",
  "Boogeyman": "",
  "Booker T": "",
  "Braun Strowman": "",
  "Bray Wyatt": "",
  "Brock Lesnar": "",
  "Bron Breakker": "",
  "Bronson Reed": "",
  "Brooks Jensen": "",
  "Brutus Creed": "",
  "Bubba Ray Dudley": "",
  "Bull Nakano": "",
  "CM Punk": "",
  "Cactus Jack": "",
  "Candice LeRae": "",
  "Carlito": "",
  "Carmella": "",
  "Carmelo Hayes": "",
  "Cedric Alexander": "",
  "Chad Gable": "",
  "Channing Lorenzo": "",
  "Charlie Dempsey": "",
  "Charlotte Flair": "",
  "Chelsea Green": "",
  "Chris Sabin": "",
  "Chyna": "",
  "Cody Rhodes": "",
  "Cora Jade": "",
  "Cruz Del Toro": "",
  "D-Lo Brown": "",
  "D-Von Dudley": "",
  "DDP": "",
  "Dakota Kai": "",
  "Damian Priest": "",
  "Dexter Lumis": "",
  "Diesel": "",
  "Doink The Clown": "",
  "Dominik Mysterio": "",
  "Dragon Lee": "",
  "Drew Mcintyre": "",
  "Dude Love": "",
  "Duke Hudson": "",
  "Dusty Rhodes": "",
  "Eddie Guerrero": "",
  "Eddy Thorpe": "",
  "Elektra Lopez": "",
  "El Grande Americano": "",
  "El Hijo Del Vikingo": "",
  "Elton Prince": "",
  "Eric Bischoff": "",
  "Erick Rowan": "",
  "Erik": "",
  "Ethan Page": "",
  "Eve Torres": "",
  "Faarooq": "",
  "Fallon Henley": "",
  "Finn Balor": "",
  "Flammer": "",
  "Gigi Dolin": "",
  "Giovanni Vinci": "",
  "Giulia": "",
  "Goldberg": "",
  "Grayson Waller": "",
  "Gunther": "",
  "Hank Walker": "",
  "Honky Tonk Man": "",
  "HulkHogan": "",
  "Ilja Dragunov": "",
  "Indi Hartwell": "",
  "Isla Dawn": "",
  "Ivar": "",
  "Ivy Nile": "",
  "Iyo Sky": "",
  "Izzi Dame": "",
  "Jacob Fatu": "",
  "Jacy Jayne": "",
  "Jade Cargill": "",
  "Jaida Parker": "",
  "Jakara Jackson": "",
  "Jake The Snake Roberts": "",
  "Jazmyn Nyx": "",
  "JBL": "",
  "JC Mateo": "",
  "JD Mcdonagh": "",
  "Jeff Hardy": "",
  "Je'von Evans": "",
  "Jesse Ventura": "",
  "Jey Uso": "",
  "Jim Neidhart": "",
  "Jimmy Uso": "",
  "Joaquin Wilde": "",
  "Joe Coffey": "",
  "Joe Gacy": "",
  "Joe Hendry": "",
  "John Cena": "",
  "Johnny Gargano": "",
  "Jordynne Grace": "",
  "Josh Briggs": "",
  "Julius Creed": "",
  "Junkyard Dog": "",
  "KSI": "",
  "Kairi Sane": "",
  "Kane": "",
  "Karl Anderson": "",
  "Karmen Petrovic": "",
  "Karrion Kross": "",
  "Katana Chance": "",
  "Kayden Carter": "",
  "Kelani Jordan": "",
  "Ken Shamrock": "",
  "Kevin Nash": "",
  "Kevin Owens": "",
  "Kiana James": "",
  "Kit Wilson": "",
  "Kofi Kingston": "",
  "Kurt Angle": "",
  "LA Knight": "",
  "La Parka": "",
  "Lash Legend": "",
  "Lex Luger": "",
  "Lexis King": "",
  "Lita": "",
  "Liv Morgan": "",
  "Logan Paul": "",
  "Lola Vice": "",
  "Ludwig Kaiser": "",
  "Luke Gallows": "",
  "Lyra Valkyria": "",
  "Macho Man Randy Savage": "",
  "Mankind": "",
  "Mark Coffey": "",
  "Mark Henry": "",
  "Maryse": "",
  "Matt Cardona": "",
  "Matt Hardy": "",
  "Maxxine Dupri": "",
  "Michelle McCool": "",
  "Michin": "",
  "Mick Foley": "",
  "Molly Holly": "",
  "Montez Ford": "",
  "Mr Iguana": "",
  "Mr Perfect": "",
  "Myles Borne": "",
  "Naomi": "",
  "Natalya": "",
  "Nathan Frazer": "",
  "New Jack": "",
  "Nia Jax": "",
  "Nikki Bella": "",
  "Nikki Cross": "",
  "Nikkita Lyons": "",
  "Noam Dar": "",
  "Oba Femi": "",
  "Omos": "",
  "Oro Mensah": "",
  "Otis": "",
  "Pat Mcafee": "",
  "Paul Orndorff": "",
  "Penta": "",
  "Pete Dunne": "",
  "Piper Niven": "",
  "Psycho Clown": "",
  "R-Truth": "",
  "Randy Orton": "",
  "Raquel Rodriguez": "",
  "Razor Ramon": "",
  "Rey Fenix": "",
  "Rey Mysterio": "",
  "Rezar": "",
  "Rhea Ripley": "",
  "Ricky Saints": "",
  "Ricky Steamboat": "",
  "Ridge Holland": "",
  "Rikishi": "",
  "Road Dogg": "",
  "Rob Van Dam": "",
  "Roddy Piper": "",
  "Roman Reigns": "",
  "Rosey": "",
  "Roxanne Perez": "",
  "Rusev": "",
  "Sami Zayn": "",
  "Sandman": "",
  "Santos Escobar": "",
  "Scarlett": "",
  "Scott Hall": "",
  "Scott Steiner": "",
  "Seth Rollins": "",
  "Shawn Michaels": "",
  "Shawn Spears": "",
  "Shayna Baszler": "",
  "Sheamus": "",
  "Shinsuke Nakamura": "",
  "Shotzi": "",
  "Sid Justice": "",
  "Sol Ruca": "",
  "Solo Sikoa": "",
  "Sonya Deville": "",
  "Stacy Keibler": "",
  "Stardust": "",
  "Stephanie Mcmahon": "",
  "Stephanie Vaquer": "",
  "Stone Cold Steve Austin": "",
  "Syxx": "",
  "Talla Tonga": "",
  "Tama Tonga": "",
  "Tamina": "",
  "Tank Ledger": "",
  "Tatum Paxley": "",
  "Tavion Hights": "",
  "Tegan Nox": "",
  "Terry Funk": "",
  "The Fiend": "",
  "The Great Khali": "",
  "The Great Muta": "",
  "The Hurricane": "",
  "The Iron Sheik": "",
  "The Miz": "",
  "The Rock": "",
  "Thea Hail": "",
  "Tiffany Stratton": "",
  "Tito Santana": "",
  "Tommaso Ciampa": "",
  "Tonga Loa": "",
  "Tony D'Angelo": "",
  "Torrie Wilson": "",
  "Trick Williams": "",
  "Triple H": "",
  "Trish Stratus": "",
  "Tyler Bate": "",
  "Tyler Breeze": "",
  "Ultimate Warrior": "",
  "Umaga": "",
  "Uncle Howdy": "",
  "Undertaker": "",
  "Vader": "",
  "Valhalla": "",
  "Victoria": "",
  "Wade Barrett": "",
  "Wendy Choo": "",
  "Wes Lee": "",
  "William Regal": "",
  "Wolfgang": "",
  "Wren Sinclair": "",
  "X-Pac": "",
  "Xavier Woods": "",
  "Yokozuna": "",
  "Yoshiki Inamura": "",
  "Zaria": "",
  "ZelinaVega": "",
  "Zoey Stark": "",
};
